# Ultralytics YOLO 🚀, GPL-3.0 license

# Parameters
nc: 3  # number of classes
depth_multiple: 0.33  # scales module repeats
width_multiple: 0.25  # scales convolution channels
max_channnels: 1024

# YOLOv8.0s backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, lymo.PatchEmbed, [96, 4]]  # 0 [b, 96, 160, 160]
  - [-1, 1, lymo.SwinStage , [96, 2, 3, 7]]  # 1 [b, 96, 160, 160]
  - [-1, 1, lymo.PatchMerging, [192]]    # 2 [b, 192, 80, 80]
  - [-1, 1, lymo.SwinStage,  [192, 2, 6, 7]]  # 3 --F0-- [b, 192, 80, 80] p3
  - [-1, 1, lymo.PatchMerging, [384]]   # 4 [b, 384, 40, 40]
  - [-1, 1, lymo.SwinStage, [384, 6, 12, 7]] # 5 --F1-- [b, 384, 40, 40] p4
  - [-1, 1, lymo.PatchMerging, [768]]   # 6 [b, 768, 20, 20]
  - [-1, 1, lymo.SwinStage, [768, 2, 24, 7]] # 7 --F2-- [b, 768, 20, 20]
  - [-1, 1, SPPF, [1024, 5]] 

# YOLOv8.0s head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 5], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 3], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 11], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 8], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[14, 17, 20], 1, Detect, [nc]]  # Detect(P3, P4, P5)





